Chore/add storybook
chingu-x/chingu-dashboard-components pull request #15
Opened 2024-12-05 16:19 UTC by JaneMoroz

2024-12-08 02:53 UTC, Dan-Y-Ko requested changes
Let's keep the folder naming consistent and use kebab-casing (for multiple words, like avatar-group)

For the ts errors was it something like this

```
The inferred type of 'Outline' cannot be named without a reference to '.pnpm/@storybook+csf@0.1.12/node_modules/@storybook/csf'. This is likely not portable. A type annotation is necessary.
```

I was able to resolve those by just adding the types that were already in the file. So like add Story type to the stories and add the meta type to the meta object.

I'm currently having an issue with @heroicons/react package when I try to install this package in a test project, I'm not sure why. I am trying to figure that out atm

This is the error I am getting

```
EPERM: operation not permitted, rename 'C:\Users\DK379\Documents\web_pages\test-project\node_modules\.pnpm\@heroicons+react@2.2.0_react@18.3.1\node_modules\@heroicons\react_tmp_24124' -> 'C:\Users\DK379\Documents\web_pages\test-project\node_modules\.pnpm\@heroicons+react@2.2.0_react@18.3.1\node_modules\@heroicons\react'
```

2024-12-08 02:53 UTC, Dan-Y-Ko commented on package.json
> +    "build-storybook:css": "tailwindcss -m -i ./src/tailwind-entry.css -o ./src/index.css",
tailwind-entry.css isn't necessary. It's the same file as the style.css. Remove the tailwind-entry.css file and replace the scripts here with style.css

2024-12-08 02:53 UTC, Dan-Y-Ko commented on package.json
> +    "storybook": "8.4.6",
Im getting an error about an unmet peerdepedency with storybook. Seems to require 8.4.7

2024-12-08 02:53 UTC, Dan-Y-Ko commented on tsconfig.json
> +    "emitDeclarationOnly": false,
Please revert the tsconfig back to the original, it is needed

2024-12-08 03:09 UTC, Dan-Y-Ko commented
nvm, I got the issue corrected. Everything is working properly on my side with the fixes I mentioned implemented, so that's all that needs to be taken care of

2024-12-08 03:27 UTC, Dan-Y-Ko commented
ok so I tested in a nextjs project and it has an issue. The width and height props on the avatar component don't really work correctly. We have to manually pass the that props to the Image component from nextjs, so we need another solution. Maybe get rid of the width and height prop from the avatar component and have it just handled from the consumer directly?

2024-12-08 10:40 UTC, JaneMoroz commented
> make the nextjs image take the dimensions of the parent div

So, I removed width/height from the 'Avatar', I think we have to give Nextjs image heigth and width everytime we use it, without width/heigth, it throws the error. I tested it in 'AuthHeader' and 'VoteCard' in 'ideation' and haven't encountered any `stretching`

2024-12-08 21:56 UTC, Dan-Y-Ko commented
> > make the nextjs image take the dimensions of the parent div
> 
> So, I removed width/height from the 'Avatar', I think we have to set Nextjs image's heigth and width everytime we use it, without width/heigth, it throws the error. I tested it in 'AuthHeader' and 'VoteCard' in 'ideation' and haven't encountered any `stretching`

I'm guessing the reason you don't see it is because you have it inside a div in the component that is constraining it?

Here's a screenshot where it's just by itself. Look carefully, it's hard to see but you there is a different shade extending the entire width.

![screenshot](https://i.imgur.com/37ls53s.png)

Do you think it's ok to leave it to the outside component to set the boundaries? It may cause weird behaviors

For example, using this code

```
<div className="w-32">
      <Avatar>
        <Image
          alt="avatar"
          src="https://gravatar.com/avatar/a6416cf1e8d0208251a732a6af75530878cdfd92b85d2de9ba6c4fec92d8a157?s=200&r=g&d=robohash"
          width={60}
          height={60}
        />
      </Avatar>
    </div>
```

it looks like this

![screenshot](https://i.imgur.com/6UrofP0.png)

2024-12-08 22:11 UTC, Dan-Y-Ko commented
I tried figuring this out but css is just not my strength lol

If you can come up with a different solution to handle transparent images, we can go with that. That's what the bg-base-200 is for.

I guess we could just create an image component in the user dashboard project with the nextjs image and add the bg-base-200 in there? and remove it from the avatar component styling

2024-12-12 09:11 UTC, JaneMoroz commented
@Dan-Y-Ko added `h-fit w-fit` so now the avatar's heigth/width will adjust to the inner content height/width (`<Image/>` in our case)

And about transparent images.... we do have `bg-base-200` added to `Avatar` and you can even add a border with `withBorder` prop, no need to add `bg-base-200` anywhere else... so not sure what you meant here:

> If you can come up with a different solution to handle transparent images, we can go with that. That's what the bg-base-200 is for.

>I guess we could just create an image component in the user dashboard project with the nextjs image component and add the bg-base-200 in there? and remove it from the avatar component styling

2024-12-13 01:28 UTC, Dan-Y-Ko approved these changes
gj :)

2024-12-13 01:28 UTC, merged